s x y z = x z (y z)
i x = x
main = ((s i) i) ((s i) i)

------------------------------------------------------------
{- 
s i i (s i i)
i (s i i) (i (s i i))
s i i (i (s i i))
i (i (s i i)) (i (i (s i i)))
i (s i i) (i (i (s i i)))
s i i (i (i (s i i)))
i (i (i (s i i))) (i (i (i (s i i))))
i (i (s i i)) (i (i (i (s i i))))
i (s i i) (i (i (i (s i i))))
s i i (i (i (i (s i i))))
i (i (i (i (s i i)))) (i (i (i (i (s i i)))))
i (i (i (s i i))) (i (i (i (i (s i i)))))
i (i (s i i)) (i (i (i (i (s i i)))))
i (s i i) (i (i (i (i (s i i)))))
s i i (i (i (i (i (s i i)))))
i (i (i (i (i (s i i))))) (i (i (i (i (i (s i i))))))
i (i (i (i (s i i)))) (i (i (i (i (i (s i i))))))
i (i (i (s i i))) (i (i (i (i (i (s i i))))))
i (i (s i i)) (i (i (i (i (i (s i i))))))
i (s i i) (i (i (i (i (i (s i i))))))
s i i (i (i (i (i (i (s i i))))))
i (i (i (i (i (i (s i i)))))) (i (i (i (i (i (i (s i i)))))))
i (i (i (i (i (s i i))))) (i (i (i (i (i (i (s i i)))))))
i (i (i (i (s i i)))) (i (i (i (i (i (i (s i i)))))))
i (i (i (s i i))) (i (i (i (i (i (i (s i i)))))))
i (i (s i i)) (i (i (i (i (i (i (s i i)))))))
i (s i i) (i (i (i (i (i (i (s i i)))))))
s i i (i (i (i (i (i (i (s i i)))))))
i (i (i (i (i (i (i (s i i))))))) (i (i (i (i (i (i (i (s i i))))))))
i (i (i (i (i (i (s i i)))))) (i (i (i (i (i (i (i (s i i))))))))
...
-}
